// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Activity struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Wid                  int64    `protobuf:"varint,2,opt,name=Wid,proto3" json:"Wid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
	ActivityType         int32    `protobuf:"varint,5,opt,name=ActivityType,proto3" json:"ActivityType,omitempty"`
	RelativeId           int64    `protobuf:"varint,6,opt,name=RelativeId,proto3" json:"RelativeId,omitempty"`
	Extra                string   `protobuf:"bytes,7,opt,name=Extra,proto3" json:"Extra,omitempty"`
	TimeStarted          int64    `protobuf:"varint,8,opt,name=TimeStarted,proto3" json:"TimeStarted,omitempty"`
	TimeEnd              int64    `protobuf:"varint,9,opt,name=TimeEnd,proto3" json:"TimeEnd,omitempty"`
	CreatedAt            int64    `protobuf:"varint,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,11,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{0}
}

func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (m *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(m, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Activity) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Activity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Activity) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Activity) GetActivityType() int32 {
	if m != nil {
		return m.ActivityType
	}
	return 0
}

func (m *Activity) GetRelativeId() int64 {
	if m != nil {
		return m.RelativeId
	}
	return 0
}

func (m *Activity) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *Activity) GetTimeStarted() int64 {
	if m != nil {
		return m.TimeStarted
	}
	return 0
}

func (m *Activity) GetTimeEnd() int64 {
	if m != nil {
		return m.TimeEnd
	}
	return 0
}

func (m *Activity) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Activity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Response struct {
	Boolean              bool     `protobuf:"varint,1,opt,name=boolean,proto3" json:"boolean,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetBoolean() bool {
	if m != nil {
		return m.Boolean
	}
	return false
}

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Query struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Wid                  int64    `protobuf:"varint,3,opt,name=wid,proto3" json:"wid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{2}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Query) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Query) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

type Activitylist struct {
	Page                 int64       `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64       `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Activities           []*Activity `protobuf:"bytes,3,rep,name=activities,proto3" json:"activities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Activitylist) Reset()         { *m = Activitylist{} }
func (m *Activitylist) String() string { return proto.CompactTextString(m) }
func (*Activitylist) ProtoMessage()    {}
func (*Activitylist) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{3}
}

func (m *Activitylist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activitylist.Unmarshal(m, b)
}
func (m *Activitylist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activitylist.Marshal(b, m, deterministic)
}
func (m *Activitylist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activitylist.Merge(m, src)
}
func (m *Activitylist) XXX_Size() int {
	return xxx_messageInfo_Activitylist.Size(m)
}
func (m *Activitylist) XXX_DiscardUnknown() {
	xxx_messageInfo_Activitylist.DiscardUnknown(m)
}

var xxx_messageInfo_Activitylist proto.InternalMessageInfo

func (m *Activitylist) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Activitylist) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Activitylist) GetActivities() []*Activity {
	if m != nil {
		return m.Activities
	}
	return nil
}

func init() {
	proto.RegisterType((*Activity)(nil), "service.Activity")
	proto.RegisterType((*Response)(nil), "service.Response")
	proto.RegisterType((*Query)(nil), "service.Query")
	proto.RegisterType((*Activitylist)(nil), "service.Activitylist")
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor_a684c9a0549e7832) }

var fileDescriptor_a684c9a0549e7832 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xd1, 0xab, 0xd3, 0x30,
	0x14, 0xc6, 0x6f, 0xdb, 0x75, 0xed, 0xce, 0x64, 0xea, 0x41, 0x21, 0x5c, 0x44, 0x4a, 0x9f, 0xfa,
	0x34, 0xbd, 0x57, 0xff, 0x81, 0xab, 0x0e, 0x29, 0x88, 0x60, 0x36, 0xf1, 0x39, 0x5b, 0x0e, 0x12,
	0xe8, 0xda, 0xd2, 0xc4, 0xb9, 0xfa, 0x07, 0xe9, 0xbf, 0x29, 0x49, 0xd3, 0x6d, 0xb2, 0x17, 0xdf,
	0xbe, 0xef, 0xf7, 0x25, 0x27, 0xcd, 0x97, 0xc2, 0x42, 0xec, 0x8c, 0x3a, 0x28, 0xd3, 0x2f, 0xdb,
	0xae, 0x31, 0x0d, 0x26, 0x9a, 0xba, 0x83, 0xda, 0x51, 0xfe, 0x3b, 0x84, 0xf4, 0xc1, 0x67, 0xb8,
	0x80, 0xb0, 0x94, 0x2c, 0xc8, 0x82, 0x22, 0xe2, 0x61, 0x29, 0xf1, 0x09, 0x44, 0xdf, 0x94, 0x64,
	0xa1, 0x03, 0x56, 0x22, 0xc2, 0xe4, 0xb3, 0xd8, 0x13, 0x8b, 0xb2, 0xa0, 0x98, 0x71, 0xa7, 0x2d,
	0xfb, 0x40, 0x7a, 0xc7, 0x26, 0x03, 0xb3, 0x1a, 0x73, 0x78, 0x34, 0x4e, 0xdd, 0xf4, 0x2d, 0xb1,
	0x38, 0x0b, 0x8a, 0x98, 0xff, 0xc3, 0xf0, 0x25, 0x00, 0xa7, 0x4a, 0x18, 0x75, 0xa0, 0x52, 0xb2,
	0xa9, 0x3b, 0xe4, 0x82, 0xe0, 0x33, 0x88, 0x57, 0x47, 0xd3, 0x09, 0x96, 0xb8, 0xc1, 0x83, 0xc1,
	0x0c, 0xe6, 0x1b, 0xb5, 0xa7, 0xb5, 0x11, 0x9d, 0x21, 0xc9, 0x52, 0xb7, 0xed, 0x12, 0x21, 0x83,
	0xc4, 0xda, 0x55, 0x2d, 0xd9, 0xcc, 0xa5, 0xa3, 0xc5, 0x17, 0x30, 0x7b, 0xdf, 0x91, 0x30, 0x24,
	0x1f, 0x0c, 0x03, 0x97, 0x9d, 0x81, 0x4d, 0xbf, 0xb6, 0xd2, 0xa7, 0xf3, 0x21, 0x3d, 0x81, 0xfc,
	0x2d, 0xa4, 0x9c, 0x74, 0xdb, 0xd4, 0x9a, 0xec, 0x09, 0xdb, 0xa6, 0xa9, 0x48, 0xd4, 0xae, 0xac,
	0x94, 0x8f, 0xd6, 0x36, 0x78, 0x2a, 0x2c, 0x54, 0x32, 0x5f, 0x41, 0xfc, 0xe5, 0x07, 0x75, 0xbd,
	0xbd, 0x8c, 0xaa, 0x25, 0x1d, 0x7d, 0xbb, 0x83, 0xb1, 0xb4, 0x52, 0x7b, 0x65, 0xfc, 0x8e, 0xc1,
	0xd8, 0xda, 0x7f, 0x2a, 0xe9, 0x3a, 0x8e, 0xb8, 0x95, 0xb9, 0x3a, 0xd7, 0x59, 0x29, 0x6d, 0x6c,
	0xe5, 0xad, 0xf8, 0x4e, 0x7e, 0x98, 0xd3, 0x96, 0x69, 0xf5, 0x8b, 0xfc, 0x28, 0xa7, 0xf1, 0x0e,
	0xc0, 0x3f, 0xbc, 0x22, 0xcd, 0xa2, 0x2c, 0x2a, 0xe6, 0xf7, 0x4f, 0x97, 0xfe, 0xed, 0x97, 0xe3,
	0x48, 0x7e, 0xb1, 0xe8, 0xfe, 0x4f, 0x00, 0x8f, 0xc7, 0x60, 0x3d, 0x2c, 0xc4, 0x3b, 0x48, 0x3e,
	0x92, 0x79, 0xd7, 0x97, 0x12, 0xaf, 0x77, 0xdf, 0x5e, 0xa3, 0xfc, 0x06, 0x5f, 0xc1, 0xe4, 0x93,
	0xfd, 0xd2, 0xc5, 0x29, 0x74, 0x3d, 0xdc, 0x3e, 0xbf, 0x5a, 0x6c, 0x2f, 0x94, 0xdf, 0xe0, 0x6b,
	0x98, 0x96, 0xb5, 0xa6, 0xce, 0xfc, 0xef, 0x11, 0xdb, 0xa9, 0xfb, 0x95, 0xdf, 0xfc, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0xf8, 0x25, 0xa4, 0xf8, 0xdc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivityServiceClient is the client API for ActivityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivityServiceClient interface {
	GetById(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*Activity, error)
	List(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Activitylist, error)
	Insert(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*Activity, error)
}

type activityServiceClient struct {
	cc *grpc.ClientConn
}

func NewActivityServiceClient(cc *grpc.ClientConn) ActivityServiceClient {
	return &activityServiceClient{cc}
}

func (c *activityServiceClient) GetById(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*Activity, error) {
	out := new(Activity)
	err := c.cc.Invoke(ctx, "/service.ActivityService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) List(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Activitylist, error) {
	out := new(Activitylist)
	err := c.cc.Invoke(ctx, "/service.ActivityService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) Insert(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*Activity, error) {
	out := new(Activity)
	err := c.cc.Invoke(ctx, "/service.ActivityService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServiceServer is the server API for ActivityService service.
type ActivityServiceServer interface {
	GetById(context.Context, *Activity) (*Activity, error)
	List(context.Context, *Query) (*Activitylist, error)
	Insert(context.Context, *Activity) (*Activity, error)
}

// UnimplementedActivityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedActivityServiceServer struct {
}

func (*UnimplementedActivityServiceServer) GetById(ctx context.Context, req *Activity) (*Activity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (*UnimplementedActivityServiceServer) List(ctx context.Context, req *Query) (*Activitylist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedActivityServiceServer) Insert(ctx context.Context, req *Activity) (*Activity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}

func RegisterActivityServiceServer(s *grpc.Server, srv ActivityServiceServer) {
	s.RegisterService(&_ActivityService_serviceDesc, srv)
}

func _ActivityService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Activity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ActivityService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).GetById(ctx, req.(*Activity))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ActivityService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).List(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Activity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ActivityService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).Insert(ctx, req.(*Activity))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActivityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.ActivityService",
	HandlerType: (*ActivityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _ActivityService_GetById_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ActivityService_List_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _ActivityService_Insert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}
