// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkin.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Checkin struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Wid                  int64    `protobuf:"varint,2,opt,name=Wid,proto3" json:"Wid,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	Wuid                 int64    `protobuf:"varint,4,opt,name=Wuid,proto3" json:"Wuid,omitempty"`
	Liner                int64    `protobuf:"varint,5,opt,name=Liner,proto3" json:"Liner,omitempty"`
	Total                int64    `protobuf:"varint,6,opt,name=Total,proto3" json:"Total,omitempty"`
	Lastcheckin          int64    `protobuf:"varint,7,opt,name=Lastcheckin,proto3" json:"Lastcheckin,omitempty"`
	CreatedAt            int64    `protobuf:"varint,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,11,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkin) Reset()         { *m = Checkin{} }
func (m *Checkin) String() string { return proto.CompactTextString(m) }
func (*Checkin) ProtoMessage()    {}
func (*Checkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_072e71e6019dc001, []int{0}
}

func (m *Checkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkin.Unmarshal(m, b)
}
func (m *Checkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkin.Marshal(b, m, deterministic)
}
func (m *Checkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkin.Merge(m, src)
}
func (m *Checkin) XXX_Size() int {
	return xxx_messageInfo_Checkin.Size(m)
}
func (m *Checkin) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkin.DiscardUnknown(m)
}

var xxx_messageInfo_Checkin proto.InternalMessageInfo

func (m *Checkin) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Checkin) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Checkin) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *Checkin) GetWuid() int64 {
	if m != nil {
		return m.Wuid
	}
	return 0
}

func (m *Checkin) GetLiner() int64 {
	if m != nil {
		return m.Liner
	}
	return 0
}

func (m *Checkin) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Checkin) GetLastcheckin() int64 {
	if m != nil {
		return m.Lastcheckin
	}
	return 0
}

func (m *Checkin) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Checkin) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Response struct {
	Boolean              bool     `protobuf:"varint,1,opt,name=boolean,proto3" json:"boolean,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_072e71e6019dc001, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetBoolean() bool {
	if m != nil {
		return m.Boolean
	}
	return false
}

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Query struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Wid                  int64    `protobuf:"varint,3,opt,name=wid,proto3" json:"wid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_072e71e6019dc001, []int{2}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Query) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Query) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

type Checkinlist struct {
	Page                 int64      `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64      `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Checkins             []*Checkin `protobuf:"bytes,3,rep,name=Checkins,proto3" json:"Checkins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Checkinlist) Reset()         { *m = Checkinlist{} }
func (m *Checkinlist) String() string { return proto.CompactTextString(m) }
func (*Checkinlist) ProtoMessage()    {}
func (*Checkinlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_072e71e6019dc001, []int{3}
}

func (m *Checkinlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkinlist.Unmarshal(m, b)
}
func (m *Checkinlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkinlist.Marshal(b, m, deterministic)
}
func (m *Checkinlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkinlist.Merge(m, src)
}
func (m *Checkinlist) XXX_Size() int {
	return xxx_messageInfo_Checkinlist.Size(m)
}
func (m *Checkinlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkinlist.DiscardUnknown(m)
}

var xxx_messageInfo_Checkinlist proto.InternalMessageInfo

func (m *Checkinlist) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Checkinlist) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Checkinlist) GetCheckins() []*Checkin {
	if m != nil {
		return m.Checkins
	}
	return nil
}

func init() {
	proto.RegisterType((*Checkin)(nil), "service.Checkin")
	proto.RegisterType((*Response)(nil), "service.Response")
	proto.RegisterType((*Query)(nil), "service.Query")
	proto.RegisterType((*Checkinlist)(nil), "service.Checkinlist")
}

func init() { proto.RegisterFile("checkin.proto", fileDescriptor_072e71e6019dc001) }

var fileDescriptor_072e71e6019dc001 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0xbf, 0x24, 0x6d, 0xd3, 0x6f, 0xc2, 0xd7, 0xaf, 0x2c, 0x3d, 0x2c, 0x45, 0xa4, 0xe4,
	0xd4, 0x83, 0x44, 0xa8, 0xbe, 0x40, 0x2d, 0x22, 0x81, 0x5e, 0x8c, 0x4a, 0xcf, 0x69, 0x76, 0xd0,
	0xc5, 0x98, 0x84, 0xec, 0xb6, 0x5a, 0x1f, 0xc7, 0xb7, 0xf3, 0x2d, 0x64, 0x27, 0xdb, 0x58, 0xec,
	0xc5, 0xdb, 0xcc, 0xef, 0x3f, 0x3b, 0xcc, 0xfc, 0x67, 0xe1, 0x5f, 0xf6, 0x84, 0xd9, 0xb3, 0x2c,
	0xa2, 0xaa, 0x2e, 0x75, 0xc9, 0x7c, 0x85, 0xf5, 0x56, 0x66, 0x18, 0x7e, 0x3a, 0xe0, 0x2f, 0x1a,
	0x89, 0x0d, 0xc0, 0x8d, 0x05, 0x77, 0x26, 0xce, 0xd4, 0x4b, 0xdc, 0x58, 0xb0, 0x21, 0x78, 0x2b,
	0x29, 0xb8, 0x4b, 0xc0, 0x84, 0xec, 0x14, 0x60, 0x9e, 0x69, 0xb9, 0x95, 0x7a, 0x17, 0x0b, 0xee,
	0x91, 0x70, 0x40, 0x18, 0x83, 0xce, 0x6a, 0x23, 0x05, 0xef, 0x90, 0x42, 0x31, 0x1b, 0x41, 0x77,
	0x29, 0x0b, 0xac, 0x79, 0x97, 0x60, 0x93, 0x18, 0x7a, 0x5f, 0xea, 0x34, 0xe7, 0xbd, 0x86, 0x52,
	0xc2, 0x26, 0x10, 0x2c, 0x53, 0xa5, 0xed, 0xac, 0xdc, 0x27, 0xed, 0x10, 0xb1, 0x13, 0xf8, 0xbb,
	0xa8, 0x31, 0xd5, 0x28, 0xe6, 0x9a, 0x03, 0xe9, 0xdf, 0xc0, 0xa8, 0x0f, 0x95, 0xb0, 0x6a, 0xd0,
	0xa8, 0x2d, 0x08, 0x2f, 0xa1, 0x9f, 0xa0, 0xaa, 0xca, 0x42, 0x21, 0xe3, 0xe0, 0xaf, 0xcb, 0x32,
	0xc7, 0xb4, 0xa0, 0x85, 0xfb, 0xc9, 0x3e, 0x35, 0x2e, 0xb4, 0x4b, 0xbb, 0x52, 0x84, 0xd7, 0xd0,
	0xbd, 0xdd, 0x60, 0xbd, 0x33, 0x23, 0xcb, 0x42, 0xe0, 0x9b, 0x75, 0xa8, 0x49, 0x0c, 0xcd, 0xe5,
	0x8b, 0xd4, 0xf6, 0x45, 0x93, 0x18, 0xeb, 0x5e, 0xe5, 0xde, 0x21, 0x13, 0x86, 0x19, 0x04, 0xd6,
	0xe7, 0x5c, 0x2a, 0x6d, 0x9c, 0xaa, 0xd2, 0x47, 0xb4, 0xbd, 0x28, 0x36, 0x4c, 0xc9, 0x77, 0xb4,
	0x9d, 0x28, 0x66, 0x67, 0xd0, 0xb7, 0xcf, 0x14, 0xf7, 0x26, 0xde, 0x34, 0x98, 0x0d, 0x23, 0x7b,
	0xbb, 0xc8, 0x0a, 0x49, 0x5b, 0x31, 0xfb, 0x70, 0xe0, 0xff, 0xfe, 0x1c, 0x77, 0x4d, 0x15, 0x3b,
	0x07, 0xff, 0x06, 0xf5, 0x95, 0x39, 0xcf, 0xd1, 0xd3, 0xf1, 0x11, 0x09, 0xff, 0xb0, 0x08, 0x3a,
	0x4b, 0x33, 0xe2, 0xa0, 0xd5, 0x68, 0xff, 0xf1, 0xe8, 0x67, 0xad, 0x59, 0x84, 0xea, 0x7b, 0x71,
	0xa1, 0xb0, 0xd6, 0xbf, 0xeb, 0xbf, 0xee, 0xd1, 0x17, 0xbc, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0x1a, 0xeb, 0x9b, 0x54, 0x93, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivityServiceClient is the client API for ActivityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivityServiceClient interface {
	GetById(ctx context.Context, in *Checkin, opts ...grpc.CallOption) (*Checkin, error)
	List(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Checkinlist, error)
	Insert(ctx context.Context, in *Checkin, opts ...grpc.CallOption) (*Checkin, error)
}

type activityServiceClient struct {
	cc *grpc.ClientConn
}

func NewActivityServiceClient(cc *grpc.ClientConn) ActivityServiceClient {
	return &activityServiceClient{cc}
}

func (c *activityServiceClient) GetById(ctx context.Context, in *Checkin, opts ...grpc.CallOption) (*Checkin, error) {
	out := new(Checkin)
	err := c.cc.Invoke(ctx, "/service.ActivityService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) List(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Checkinlist, error) {
	out := new(Checkinlist)
	err := c.cc.Invoke(ctx, "/service.ActivityService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) Insert(ctx context.Context, in *Checkin, opts ...grpc.CallOption) (*Checkin, error) {
	out := new(Checkin)
	err := c.cc.Invoke(ctx, "/service.ActivityService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServiceServer is the server API for ActivityService service.
type ActivityServiceServer interface {
	GetById(context.Context, *Checkin) (*Checkin, error)
	List(context.Context, *Query) (*Checkinlist, error)
	Insert(context.Context, *Checkin) (*Checkin, error)
}

// UnimplementedActivityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedActivityServiceServer struct {
}

func (*UnimplementedActivityServiceServer) GetById(ctx context.Context, req *Checkin) (*Checkin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (*UnimplementedActivityServiceServer) List(ctx context.Context, req *Query) (*Checkinlist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedActivityServiceServer) Insert(ctx context.Context, req *Checkin) (*Checkin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}

func RegisterActivityServiceServer(s *grpc.Server, srv ActivityServiceServer) {
	s.RegisterService(&_ActivityService_serviceDesc, srv)
}

func _ActivityService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Checkin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ActivityService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).GetById(ctx, req.(*Checkin))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ActivityService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).List(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Checkin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ActivityService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).Insert(ctx, req.(*Checkin))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActivityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.ActivityService",
	HandlerType: (*ActivityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _ActivityService_GetById_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ActivityService_List_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _ActivityService_Insert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkin.proto",
}
